spring:
  application:
    name: eureka-service

server:
  port: 8302

eureka:
  client:
    register-with-eureka: false  #  this project is not a client so disable it
    fetch-registry: false         #  don't fetch me the registry infomation
    #service-url:
    #  defaultZone: http://localhost:8888/eureka
    server:
      waitTimeInMsWhenSyncEmpty: 0

zuul:
  prefix: /api
  routes:
    db-service:
      path: /db-service/**
      url: http://localhost:8300
    stock-service:
      path: /stock-service/**
      url: http://localhost:8301